---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: licenses, licensing, subscriptions, annual subscription, paygo, hourly subscription 
summary: 在您的 14 天免費試用結束後、有兩種方式可以支付同步關係的費用。第一個選項是從 AWS 或 Azure 訂閱、以隨用隨付或每年付費。第二種選擇是直接向 NetApp 購買授權。 
---
= 授權總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在您的 14 天免費試用結束後、有兩種方式可以支付同步關係的費用。第一個選項是從 AWS 或 Azure 訂閱、以隨用隨付或每年付費。第二種選擇是直接向 NetApp 購買授權。



== 市場訂閱

訂閱 Cloud Sync AWS 或 Azure 提供的支援服務、可讓您以每小時的費率付款、或是每年付費。 link:task-licensing.html["您可以透過 AWS 或 Azure 訂閱"]（視您要帳單的地點而定）。



=== 每小時訂閱

透過每小時隨用隨付訂閱、您將根據所建立的同步關係數、每小時收取一次費用。

* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["在 Azure 中檢視定價"^]
* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["在 AWS 中檢視隨用隨付定價"^]




=== 一年訂閱

一年訂閱可提供 20 種同步關係的授權、您可以預付費用。如果您的同步關係超過20個、而且您已透過AWS訂閱、則需在一小時內支付額外的關係費用。

https://aws.amazon.com/marketplace/pp/B06XX5V3M2["在 AWS 中檢視年度定價"^]



== NetApp 授權

另一種預付同步關係費用的方法是直接向 NetApp 購買授權。每個授權可讓您建立最多 20 個同步關係。

您可以搭配 AWS 或 Azure 訂閱使用這些授權。例如、如果您有 25 個同步關係、您可以使用授權支付前 20 個同步關係的費用、然後從 AWS 或 Azure 購買剩餘的 5 個同步關係。

link:task-licensing.html["瞭解如何購買授權、並將其新增 Cloud Sync 至"]。



=== 授權條款

購買「自帶授權（ BYOL ）到 Cloud Sync 該服務」的客戶、應注意授權權利的相關限制。

* 自交付日起一年內、客戶有權使用 BYOL 授權。
* 客戶有權利用 BYOL 授權、在來源與目標之間建立且不超過 20 個個別連線（每個連線都是「同步關係」）。
* 客戶的權利將在一年授權期限結束時到期、無論客戶是否達到 20 個同步關係限制。
* 如果客戶選擇續約其授權、則與先前授權授予相關的未使用同步關係不會滾存至授權續約。

