---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: 您可以透過 Cloud Sync 各種資源（包括論壇、聊天室服務和影片）、取得有關解決此問題的協助、並尋找更多資訊。 
---
= 技術常見問題集 Cloud Sync
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想要快速回答問題、這個常見問題集就能幫上忙。



== 快速入門

下列問題與 Cloud Sync 使用指南有關。



=== 如何運作呢？ Cloud Sync

使用 NetApp 資料代理軟體、將資料從來源同步至目標（這稱為 _sync 關係 _ ） Cloud Sync 。

資料代理人群組可控制來源與目標之間的同步關係。設定同步關係之後 Cloud Sync 、即可分析來源系統、並將其分成多個複寫串流、以推送至您所選的目標資料。

初始複本之後、服務會根據您設定的排程同步任何變更的資料。



=== 14 天免費試用如何運作？

14 天免費試用版會在您註冊 Cloud Sync 使用 VMware 服務時開始。您不需支付 NetApp 的 Cloud Sync 費用、即可建立 14 天的穩固關係。不過、您部署的任何資料代理人的所有資源費用仍適用。



=== 此功能需要多少成本？ Cloud Sync

有兩種成本與 Cloud Sync 使用效益有關：服務費用和資源費用。

* 服務費用 *

針對隨用隨付定價、 Cloud Sync 根據您所建立的同步關係數量、不收取每小時的服務費用。

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["在 AWS 中檢視隨用隨付定價"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["在 AWS 中檢視年度定價"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["在 Azure 中檢視定價"^]


您也可以透過 NetApp 代表取得此套軟體授權。 Cloud Sync每個授權可在 12 個月內建立 20 個同步關係。

link:concept-licensing.html["深入瞭解授權"]。


NOTE: 不需再為其提供任何功能、Cloud Sync Cloud Volumes Service Azure NetApp Files

* 資源費用 *

資源費用與在雲端執行資料代理商所需的運算和儲存成本有關。



=== 如何收費？ Cloud Sync

在您的 14 天免費試用結束後、有兩種方式可以支付同步關係的費用。第一個選項是向 AWS 或 Azure 訂閱、讓您可以隨用隨付或每年付費。第二種選擇是直接向 NetApp 購買授權。



=== 我可以在 Cloud Sync 雲端以外使用這個功能嗎？

是的、 Cloud Sync 您可以在非雲端架構中使用來源和目標可以駐留在內部部署、資料代理軟體也可以駐留在內部。

請注意以下關於 Cloud Sync 在雲端外部使用功能的重點：

* 資料代理人群組需要網際網路連線才能與Cloud Sync 該服務進行通訊。
* 如果您不直接向 NetApp 購買授權、您將需要 AWS 或 Azure 帳戶來 Cloud Sync 支付 PAYGO 服務費用。




=== 我該如何存取 Cloud Sync 才能存取的問題？

Cloud Manager 可在 * Sync* 索引標籤中找到這個解決方案。 Cloud Sync



=== 什麼是資料代理群組？

每個資料代理程式都屬於資料代理程式群組。將資料代理人集中在一起、有助於提升同步關係的效能。



== 支援的來源和目標

下列問題與同步關係中支援的來源和目標有關。



=== 哪些來源和目標 Cloud Sync 不支援呢？

支援多種不同類型的同步關係。 Cloud Sync link:reference-supported-relationships.html["檢視完整清單"]。



=== 哪些 NFS 和 SMB 版本 Cloud Sync 支援呢？

支援 NFS 版本 3 及更新版本、以及 SMB 版本 1 及更新版本。 Cloud Sync

link:reference-requirements.html["深入瞭解同步需求"]。



=== 當 Amazon S3 成為目標時、資料是否可以分層至特定的 S3 儲存類別？

是的、當 AWS S3 為目標時、您可以選擇特定的 S3 儲存類別：

* 標準（這是預設類別）
* 智慧分層
* 標準非常用存取
* 單一區域不常用存取
* Glacier Deep 歸檔
* Glacier彈性擷取
* Glacier即時擷取




=== Azure Blob 儲存設備的儲存層又如何？

當 Blob 容器為目標時、您可以選擇特定的 Azure Blob 儲存層：

* 熱儲存
* 超酷儲存設備




=== 您是否支援Google Cloud儲存層？

是的、當Google Cloud Storage資源桶成為目標時、您可以選擇特定的儲存類別：

* 標準
* 近線
* 冷線
* 歸檔




== 網路

下列問題與 Cloud Sync 關於功能的網路需求有關。



=== 哪些網路需求 Cloud Sync 是關於功能的？

由於此環境要求資料代理群組透過所選的傳輸協定或物件儲存API（Amazon S3、Azure Blob、IBM Cloud Object Storage）、與來源和目標連線。Cloud Sync

此外、資料代理人群組需要透過連接埠443的傳出網際網路連線、以便與Cloud Sync 該服務進行通訊、並聯絡其他服務與儲存庫。

如需詳細資料、 link:reference-networking.html["檢閱網路需求"]。



=== 我可以將 Proxy 伺服器與資料代理程式搭配使用嗎？

是的。

支援 Proxy 伺服器、無論是否具備基本驗證。 Cloud Sync如果您在部署資料代理程式時指定 Proxy 伺服器、則來自資料代理程式的所有 HTTP 和 HTTPS 流量都會透過 Proxy 路由傳送。請注意、 NFS 或 SMB 等非 HTTP 流量無法透過 Proxy 伺服器路由傳送。

唯一的 Proxy 伺服器限制是使用即時資料加密搭配 NFS 或 Azure NetApp Files 不同步關係。加密資料會透過 HTTPS 傳送、無法透過 Proxy 伺服器路由傳送。



== 資料同步

下列問題與資料同步的運作方式有關。



=== 同步處理的頻率為何？

預設排程設定為每日同步。初始同步之後、您可以：

* 將同步排程修改為所需的天數、小時數或分鐘數
* 停用同步排程
* 刪除同步排程（不會遺失任何資料；只會移除同步關係）




=== 最低同步排程是多少？

您可以排程關係、每 1 分鐘同步一次資料。



=== 當檔案無法同步時、資料代理群組是否會重試？還是超時？

當單一檔案無法傳輸時、資料代理群組不會逾時。相反地、資料代理群組會在跳過檔案之前重試3次。重試值可在同步關係的設定中設定。

link:task-managing-relationships.html#changing-the-settings-for-a-sync-relationship["瞭解如何變更同步關係的設定"]。



=== 如果我有很大的資料集該怎麼辦？

如果單一目錄包含60、000個以上的檔案、請寄送電子郵件至ng-cloudsync-support@netapp.com（請與我們聯絡）、以便我們協助您設定資料代理群組來處理有效負載。我們可能需要新增額外的記憶體至資料代理群組。

請注意、掛載點中的檔案總數沒有限制。擁有60萬個以上檔案的大型目錄需要額外的記憶體、無論其在階層架構中的層級為何（上層目錄或子目錄）。



== 安全性

下列與安全性有關的問題。



=== 是否安全無虞？ Cloud Sync

是的。所有 Cloud Sync 的服務網路連線都是使用來完成 https://aws.amazon.com/sqs/["Amazon Simple Queue Service （ SQS ）"^]。

資料代理人群組與Amazon S3、Azure Blob、Google Cloud Storage和IBM Cloud Object Storage之間的所有通訊都是透過HTTPS傳輸協定進行。

如果 Cloud Sync 您使用的是內部部署（來源或目的地）系統的功能、以下是幾個建議的連線選項：

* AWS Direct Connect 、 Azure ExpressRoute 或 Google Cloud InterConnect 連線、非網際網路路由（而且只能與您指定的雲端網路通訊）
* 內部部署閘道裝置與雲端網路之間的 VPN 連線
* 若要使用 S3 儲存區、 Azure Blob 儲存設備或 Google Cloud Storage 、 Amazon Private S3 端點、 Azure Virtual Network 服務端點或私有 Google Access 進行額外安全的資料傳輸。


以上任何一種方法都會在內部部署的NAS伺服器和Cloud Sync 一個可靠的資料代理群組之間建立安全的連線。



=== 資料是否以 Cloud Sync 不加密的方式加密？

* 支援來源與目標 NFS 伺服器之間的資料傳輸加密。 Cloud Sync link:task-nfs-encryption.html["深入瞭解"]。
* 對於SMB、Cloud Sync 支援伺服器端加密的SMB 3.0和3.11資料。將加密資料從來源複製到資料保持加密的目標。Cloud Sync
+
無法加密SMB資料本身。Cloud Sync

* 當 Amazon S3 儲存區是同步關係的目標時、您可以選擇是否使用 AWS 加密或 AES-256 加密來啟用資料加密。




== 權限

下列問題與資料權限有關。



=== SMB 資料權限是否同步至目標位置？

您可以設定Cloud Sync 支援功能、在來源SMB共用區和目標SMB共用區之間、以及從來源SMB共用區到物件儲存區之間保留存取控制清單（ACL除外ONTAP ）。


NOTE: 不支援將ACL從物件儲存區複製到SMB共用區。Cloud Sync

link:task-copying-acls.html["瞭解如何在 SMB 共用區之間複製 ACL"]。



=== NFS 資料權限是否同步至目標位置？

下列項目可自動複製 NFS 伺服器之間的 NFS 權限： Cloud Sync

* NFS 版本 3 ： Cloud Sync 此功能可複製權限和使用者群組擁有者。
* NFS 第 4 版： Cloud Sync 以程式複製 ACL 。




== 物件儲存中繼資料

針對下列類型的同步關係、將物件儲存中繼資料從來源複製到目標：Cloud Sync

* Amazon S3 -> Amazon S3 ^1^
* Amazon S3 -> StorageGRID
* 支援：-> Amazon S3 StorageGRID
* 《》->《StorageGRID StorageGRID
* 資料中心-> Google Cloud Storage StorageGRID
* Google Cloud Storage -> StorageGRID 功能
* Google Cloud Storage -> IBM Cloud Object Storage（IBM雲端物件儲存設備）^1^
* Google Cloud Storage -> Amazon S3 ^1^
* Amazon S3 -> Google Cloud Storage
* IBM Cloud Object Storage -> Google Cloud Storage
* 《》->《IBM Cloud Object Storage》StorageGRID
* IBM Cloud Object Storage -> StorageGRID
* IBM Cloud Object Storage -> IBM Cloud Object Storage


您必須在這些同步關係中 link:task-creating-relationships.html["建立同步關係時、請啟用「複製物件」設定"]。



== 效能

下列問題與 Cloud Sync 效能不一致有關。



=== 同步關係的進度指標代表什麼？

同步關係顯示資料代理群組網路卡的處理量。如果您使用多個資料代理人來加速同步效能、則處理量是所有流量的總和。此處理量每 20 秒重新整理一次。



=== 我遇到效能問題。我們可以限制並行傳輸的數量嗎？

如果您有非常大的檔案（每個都有多個Tib）、可能需要很長時間才能完成傳輸程序、而且效能可能會受到影響。

限制並行傳輸的數量有助於提高效率。mailto ： ng-cloudsync-support@netapp.com [ 請聯絡我們尋求協助 ] 。



=== 為什麼 Azure NetApp Files 我使用 VMware 時效能不佳？

當您將資料同步至 Azure NetApp Files 或從 VMware 同步時、如果磁碟服務層級為「 Standard （標準）」、您可能會遇到故障和效能問題。

將服務層級變更為 Premium 或 Ultra 、以提升同步效能。

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["深入瞭 Azure NetApp Files 解有關服務層級和處理量的資訊"^]。



=== 為什麼 Cloud Volumes Service 我使用適用於 AWS 的解決方法時效能不佳？

當您在雲端磁碟區之間或從雲端磁碟區同步資料時、如果雲端磁碟區的效能等級為「 Standard （標準）」、可能會發生故障和效能問題。

將「服務層級」變更為「進階」或「極致」、以增強同步效能。



=== 群組中需要多少個資料代理人？

當您建立新關係時、首先要從群組中的單一資料代理程式開始（除非您選取屬於加速同步關係的現有資料代理程式）。在許多情況下、單一資料代理程式可滿足同步關係的效能要求。如果沒有、您可以在群組中新增額外的資料代理人、以加速同步效能。但您應該先檢查其他可能影響同步效能的因素。

多種因素可能會影響資料傳輸效能。整體同步效能可能會因為網路頻寬、延遲和網路拓撲、以及資料代理 VM 規格和儲存系統效能而受到影響。例如、群組中的單一資料代理程式可以達到100 MB/s、而目標上的磁碟處理量可能只允許64 MB/s因此、資料代理人群組會持續嘗試複製資料、但目標無法達到資料代理人群組的效能。

因此、請務必檢查網路效能和目標磁碟處理量。

然後、您可以考慮在群組中新增額外的資料代理人、以共享該關係的負載、藉此加速同步效能。 link:task-managing-relationships.html#accelerating-sync-performance["瞭解如何加速同步效能"]。



== 刪除物件

下列問題與刪除來源和目標的同步關係和資料有關。



=== 如果我刪除 Cloud Sync 我的不確定關係、會發生什麼事？

刪除關係會停止所有未來的資料同步、並終止付款。同步至目標的任何資料都會維持原樣。



=== 如果我從來源伺服器刪除某些內容、會發生什麼事？是否也從目標中移除？

根據預設、如果您有作用中的同步關係、則在下次同步處理期間、從來源伺服器刪除的項目不會從目標中刪除。但每個關係的同步設定中都有一個選項、您可以定義 Cloud Sync 如果檔案從來源中刪除、將會刪除目標位置的檔案。

link:task-managing-relationships.html#changing-the-settings-for-a-sync-relationship["瞭解如何變更同步關係的設定"]。



=== 如果我從目標中刪除某項內容、會發生什麼事？是否也從來源移除？

如果項目從目標中刪除、則不會從來源中移除。這種關係是單向的、從來源到目標。在下一個同步週期中 Cloud Sync 、 Sync-比較 來源與目標、找出項目遺失、 Cloud Sync 並再次將其從來源複製到目標。



== 疑難排解

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["NetApp 知識庫 Cloud Sync ：解決常見問題集：支援與疑難排解"^]



== 資料代理商深入探討

下列問題與資料代理程式有關。



=== 您可以說明資料代理商的架構嗎？

當然、以下是最重要的幾點：

* 資料代理程式是在 Linux 主機上執行的 node.js 應用程式。
* 下列項目可部署資料代理程式： Cloud Sync
+
** AWS ：使用 AWS CloudForation 範本
** Azure ：來自 Azure 資源管理程式
** Google ：來自 Google Cloud Deployment Manager
** 如果您使用自己的 Linux 主機、則需要手動安裝軟體


* 資料代理軟體會自動升級至最新版本。
* 資料代理商使用 AWS SQS 作為可靠且安全的通訊通道、並用於控制和監控。SQS 也提供持續性層。
* 您可以新增其他資料代理人至群組、以提高傳輸速度並增加高可用度。如果某個資料代理程式故障、就會有服務恢復功能。

